config/routes.rb
Rails.application.routes.draw do
  resources :groups, only: [:index, :show, :new, :create] do
    resources :documents, only: [:show, :create] do
      resources :questions, only: [:show, :create] do
        resources :answers, only: [:show, :create] do
          resources :votes, only: [:create]
        end
      end
    end
  end

  post 'groups/:id/join' => 'groups#join', as: :join_group
  post 'groups/:id/invite' => 'groups#invite', as: :group_invite

  root 'home#show'
  devise_for :users

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
  belongs_to :user
  has_many :votes

  def score
    score = 0
    self.votes.each do |vote|
      score += vote.value
    end
    score
  end
end

app/models/document.rb
class Document < ActiveRecord::Base
  belongs_to :group
  has_one :owner, class_name: 'User', foreign_key: 'owner_id'
  has_many :questions
end

app/models/group.rb
class Group < ActiveRecord::Base
  has_and_belongs_to_many :users
  has_many :documents
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :document
  has_many :answers
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :answers
  has_many :votes
  has_and_belongs_to_many :groups


  def voted_for(answer)
    self.votes.each do |vote|
      return true if vote.answer == answer
    end

    false
  end

  def has_contributed_to(document)
    document.questions.each do |question|
      question.answers.each do |answer|
        return true if answer.user == self
      end
    end

    false
  end
end

app/models/users_groups.rb
class UsersGroups < ActiveRecord::Base
  belongs_to :user
  belongs_to :group
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :answer
  belongs_to :user
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def create
    @question = Question.find params[:question_id]

    answer = Answer.create answer_params
    answer.user = current_user

    @question.answers << answer

    redirect_to group_document_question_path(@question.document.group, @question.document, @question)
  end

  private
  def answer_params
    params.require(:answer).permit(:text)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  def show
    @group = Group.find params[:group_id]
    @document = Document.find params[:id]

    @pipeline = HTML::Pipeline.new [HTML::Pipeline::MarkdownFilter]
  end

  def create
    @group = Group.find params[:group_id]
    @group.documents.create document_params

    redirect_to @group
  end

  private
  def document_params
    params.require(:document).permit(:name)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!

  def index
    @groups = current_user.groups
  end

  def show
    @group = Group.find params[:id]
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.create group_params
    current_user.groups << @group

    redirect_to groups_path
  end

  def join
    @group = Group.find params[:id]
    current_user.groups << @group

    redirect_to @group
  end

  def invite
    @group = Group.find params[:id]
    @email = params[:email]
    User.find_by(email: @email).groups << @group if User.find_by(email: @email).present?
    UserMailer.invite_user(@email, @group).deliver

    redirect_to @group
  end

  private
  def group_params
    params.require(:group).permit(:name)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
    if user_signed_in?
      redirect_to groups_path
    end
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def show
    @group = Group.find params[:group_id]
    @document = Document.find params[:document_id]
    @question = Question.find params[:id]

    @answers = @question.answers.sort_by {|ans| -ans.score }

    @pipeline = HTML::Pipeline.new [HTML::Pipeline::MarkdownFilter]
  end

  def create
    @document = Document.find params[:document_id]

    @document.questions.create question_params

    redirect_to group_document_path(@document.group, @document)
  end

  private
  def question_params
    params.require(:question).permit(:text)
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  def create
    @answer = Answer.find params[:answer_id]

    unless Vote.find_by(user: current_user, answer: @answer).present?
      @answer.votes.create value: params[:value], user: current_user
    end

    redirect_to group_document_question_path(@answer.question.document.group, @answer.question.document, @answer.question)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/answers/create.html.erb
<h1>Answers#create</h1>
<p>Find me in app/views/answers/create.html.erb</p>

app/views/answers/new.html.erb
<h1>Answers#new</h1>
<p>Find me in app/views/answers/new.html.erb</p>

app/views/answers/show.html.erb
<h1>Answers#show</h1>
<p>Find me in app/views/answers/show.html.erb</p>

app/views/documents/show.html.slim
div class="row"
  div class="medium-6 medium-centered columns panel large-6 large-centered columns panel text-center"
    = image_tag "newdocumenticon.png"
    h4= @document.name

    - @document.questions.each do |q|
      - if q.answers.count > 0
        div class="panel" style="background-color: #fff; border: 2px solid green"
          == @pipeline.call(q.text)[:output].to_s
          div style="margin:auto; width: 28%"
            = image_tag "answeredIcon.png", class: "left", style: "margin-right: 5px; padding-top: 3px"
            h5 class="left" style="color: green" Answered
          = link_to "View Question", group_document_question_path(@group, @document, q), class: "button expand"
      - else
        div class="panel" style="background-color: #FFF; border: 2px solid red"
          == @pipeline.call(q.text)[:output].to_s
          div style="margin:auto; width: 30%"
            = image_tag "answerNeededIcon.png", class: "left", style: "margin-right: 5px; padding-top: 3px"
            h5 class="left" style="color: red" Answer This
          = link_to "View Question", group_document_question_path(@group, @document, q), class: "button expand"

  div class="medium-6 medium-centered columns panel large-6 large-centered text-center" style="overflow: auto"
    = image_tag "newquestionicon.png"
    h4= "Create New Question"
    = form_for @document.questions.build, url: group_document_questions_path(@group, @document, @document.questions.build) do |f|
      = f.label :text, class: "formlabel"
      = f.text_area :text
      = f.submit class: "button expand"
    = link_to "Back to #{@document.group.name}", @document.group

app/views/groups/index.html.slim
div class="row"
  div class="medium-6 medium-centered columns panel large-6 large-centered columns panel text-center" style="overflow: auto"
    = image_tag "newgroupicon.png"
    h4= "Groups"
    p class="large-12 columns panel"
      = link_to "Create New Group", new_group_path, class: "button expand"

    - @groups.each do |group|
        div class="large-12 columns panel" style="background-color:#FFF"
          span class="left" = link_to group.name, group
          span class="right"= pluralize(group.documents.count, " Document")

app/views/groups/new.html.slim
div class="medium-6 medium-centered columns panel large-6 large-centered columns panel text-center" style="overflow: auto"
  = image_tag "newgroupicon.png"
  h4= "Create New Group"
  = form_for @group do |f|
    = f.label :name
    = f.text_field :name
    = f.submit class: "button expand"

app/views/groups/show.html.slim
div class="row"
  div class="medium-6 medium-centered columns panel large-6 large-centered text-center"
    = image_tag "documentlistlogo.png"
    p
    h4= @group.name
    - if @group.users.include? current_user
      ul style="list-style: none; margin-left: 15px; margin-right: 15px"
        - @group.documents.each do |doc|
          div class="row"
            div class="medium-12 columns panel large-12 text-center" style="background-color:#FFF"
              span class="left" = link_to doc.name, [@group, doc]
              span class="right" = pluralize(doc.questions.count, " Question")
        = link_to "Back to groups", groups_url


    - else
      p= link_to "Request Membership", join_group_path, method: :post

  - if @group.users.include? current_user
    div class="medium-6 medium-centered columns panel large-6 large-centered text-center" style="overflow: auto"
      = image_tag "newdocumenticon.png"
      p
      h4= "Create New Document"
      = form_for([@group, @group.documents.build]) do |f|
        = f.label :name
        = f.text_field :name
        = f.submit class: "button expand"

    div class="medium-6 medium-centered columns panel large-6 large-centered text-center" style="overflow: auto"
      = image_tag "profilelogo.png"
      p
      h4= "Invite User"
      = form_tag(group_invite_path, method: "post") do
        = label_tag(:email, "Email")
        = text_field_tag(:email)
        = submit_tag("Invite User", class: "button expand")

app/views/home/show.html.erb
<div class="row">
  <div class="medium-5 large-5 columns text-center" style="margin-top: 100px">
    <%= image_tag "logo.png" %>
  </div>
  <div class="medium-7 large-7 columns" style="margin-top: 100px">
    <br/>
    <br/>
    <h1>Create study guides</h3>
    <h3>And keep freeloaders out.</h4>
    <br/>
    <%= link_to "Sign In", new_user_session_path, class:"button [radius round]", 
      style:"width: 175px; height: 50px; margin-right: 50px" %>

    <%= link_to "Register", new_user_registration_path, class:"button [radius round]", 
      style:"width: 175px; height: 50px" %>
  </div>
</div>

app/views/questions/show.html.slim
div class="row"
  div class="medium-6 medium-centered columns panel large-6 large-centered text-center"
    p= image_tag "questionsicon.png"
    h4 Question
    div class="panel" style="background-color: #FFF"
      == @pipeline.call(@question.text)[:output].to_s

  div class="medium-6 medium-centered columns panel large-6 large-centered text-center"
    p= image_tag "answersmultipleicon.png"
    h4 Answers
    - if current_user.has_contributed_to @question.document
      - @answers.each do |ans|
        div class="panel" style="background-color: #FFF; overflow: auto"
          p class="text-left"= ans.text
          div class="left score"
            span= ans.score.to_s
          - unless current_user.voted_for ans
            = button_to " ", group_document_question_answer_votes_path(@question.document.group, @question.document, @question, ans, ans.votes.build, params: {value: 1}), id: "upvoteButton", class: "left"
            = button_to " ", group_document_question_answer_votes_path(@question.document.group, @question.document, @question, ans, ans.votes.build, params: {value: -1}), id: "downvoteButton", class: "left"
          span class="right" Submitted by #{ans.user.name} on #{ans.created_at.strftime("%m/%d at %I:%M%p")}
    - else
        = image_tag "answerNeededIcon.png", class: "left", style: "margin-right: 17px; padding-top: 3px"
        h5 class="left" style="color: red" You must contribute first before you can view answers.
        br
        br


  div class="medium-6 medium-centered columns panel large-6 large-centered text-center" style="overflow: auto"
    p= image_tag "newquestionicon.png"
    h4= "Create Answer"
    = form_for @question.answers.build, url: group_document_question_answers_path(@group, @document, @question, @question.answers.build) do |f|
      = f.label :text
      = f.text_area :text
      = f.submit class: "button expand"
    = link_to "Back to #{@document.name}", [@question.document.group, @question.document]

app/views/votes/create.html.erb
<h1>Votes#create</h1>
<p>Find me in app/views/votes/create.html.erb</p>